packages: []
catalogs:
  cli:
    bumpp: ^10.3.1
    code-finder: ^0.2.1
    pncat: ^0.7.4
    taze: ^19.9.0
  frontend:
    react: ^19.2.0
  lint:
    '@antfu/eslint-config': ^6.2.0
    '@eslint-react/eslint-plugin': ^2.2.4
    eslint: ^9.38.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  raycast:
    '@raycast/api': ^1.103.5
    '@raycast/utils': ^2.2.2
  script:
    tsx: ^4.20.6
  test:
    vitest: ^4.0.5
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.9.2
    '@types/react': ^19.2.2
  utils:
    lru-cache: ^11.2.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - better-sqlite3
